name: Build milan images
on:
  push: # Build when push
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5' # Start build every friday

jobs:
  build-image:
    strategy:
      matrix:
        version: ["default"]

    runs-on: ubuntu-latest
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4
        
      - name: Create artifact directory
        run: |
            mkdir out
        
      - name: Substitute placeholders in configs
        run: |
           find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Install pmbootstrap from git
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Set up pmaports
        run: |
          echo -e '\n\n' | pmbootstrap init || true
          
      - name: Build the huawei-milan without DE
        run: |
           cp huawei-milan.cfg ~/.config/pmbootstrap_v3.cfg
           pmbootstrap install --password 147147
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-huawei-milan.img
           cp /tmp/postmarketOS-export/huawei-milan.img out/rootfs-huawei-milan-none.img

      - name: Breakpoint if tests failed for huawei-milan without DE
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: nixxizlab
      
      - name: Upload artifacts huawei-milan without DE
        uses: actions/upload-artifact@v4
        with:
           name: huawei-milan-none
           path: out/*.img*
           retention-days: 7

      - name: Build the huawei-milan with KDE Plasma Desktop
        run: |
           yes | pmbootstrap zap
           rm -r out/*
           pmbootstrap install --password 147147 --add postmarketos-ui-plasma-desktop
           cat /home/runner/.local/var/pmbootstrap/log.txt
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-huawei-milan.img
           cp /tmp/postmarketOS-export/huawei-milan.img out/rootfs-huawei-milan-plasma.img

      - name: Breakpoint if tests failed for huawei-milan with KDE Plasma Desktop
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: nixxizlab
      
      - name: Upload artifacts huawei-milan with KDE Plasma Desktop
        uses: actions/upload-artifact@v4
        with:
           name: huawei-milan-plasma
           path: out/*.img*
           retention-days: 7
            
      - name: Build the huawei-milan with GNOME
        run: |
           yes | pmbootstrap zap
           rm -r out/*
           pmbootstrap install --password 147147 --add postmarketos-ui-gnome
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-huawei-milan.img
           cp /tmp/postmarketOS-export/huawei-milan.img out/rootfs-huawei-milan-gnome.img

      - name: Breakpoint if tests failed for huawei-milan with GNOME
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: nixxizlab
            
      - name: Upload artifacts huawei-milan with GNOME
        uses: actions/upload-artifact@v4
        with:
           name: huawei-milan-gnome
           path: out/*.img*
           retention-days: 7
           
      - name: Copy huawei-milan kernel
        run: |
           rm -r out/*
           cp ~/.local/var/pmbootstrap/packages/edge/aarch64/linux-postmarketos-qcom-sm8250-milan-*.apk out/
      
      - name: Upload artifacts huawei-milan kernel
        uses: actions/upload-artifact@v4
        with:
           name: huawei-milan-kernel
           path: out/*.apk
           retention-days: 7



        

        
